### ISSUE TITLE
Riscv64 support

### ISSUE THREAD

**Issue by kirana1996** [Jadhusan-S/Python3-Firewall#1]
Hi, 
         I am build this on riscv platform, but not able to start build getting error message.

$ python3 main.py
Not enough interfaces

installed all dependencies.
Can you tell any thing i missed.

thanks,

**Comment by Jadhusan24** [comment]
Hi Kirana,
By default 4 Network Interface needed to start the program.
And its also customizable in [line 70](https://github.com/Jadhusan-S/Python3-Firewall/blob/67d6cf60f54c31b8f5105afd61bf6ce4dec12e3b/main.py#L70) of main.py file


ps - when you attach the NIC or VNIC it will automatically detects them.

**Comment by Jadhusan-S** [comment]
1.
